spring:
  application:
    name: order-service
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://order-db:5432/orderdb}
    username: ${SPRING_DATASOURCE_USERNAME:order}
    password: ${SPRING_DATASOURCE_PASSWORD:order}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 8083

logging:
  level:
    com.example.orderservice: INFO
    org.springframework.web: INFO
